### ISSUE TITLE
Damn __init__

### ISSUE THREAD

**Issue by beridel** [beridel/fast_matched_filter#2]
When importing, you still get:
```
In [1]: import fast_matched_filter as fmf

In [2]: fmf.
**fmf.fast_matched_filter**  fmf.matched_filter       fmf.test_matched_filter
```

Isn't there any way to just have:
```
In [2]: fmf.
fmf.matched_filter       fmf.test_matched_filter
```

__init__.py will be the death of me...

**Comment by calum-chamberlain** [comment]
Ah, darn, I thought I had got that - will play more.

**Comment by calum-chamberlain** [comment]
Ah hack-ish, but useable way to do this is to have a __init__.py file like this:
```python
"""
init file for fast_matched_filter library
"""

from .fast_matched_filter import matched_filter, test_matched_filter

del fast_matched_filter

__all__ = [matched_filter, test_matched_filter]

```
The line:
```python
del fast_matched_filter
```
removes that from the namespace, but keeps the two functions callable. This should be fine if the package stays small.

**Comment by beridel** [comment]
I guess the follow-up question is: is that first case what typically happens?  Because it seems quite redundant.  And if that is not the usual case, what is different here?

**Comment by calum-chamberlain** [comment]
I think it is normal for the submodule to be added to the namespace - you would usually (without the convenience imports used here) import the functions using:
```python
from fast_matched_filter.fast_matched_filter import test_matched_filter, matched_filter
```
Which is slightly annoying - if this stays as a one-file (from a Python perspective) package then I would use the convenience imports in the `__init__.py` file and delete the submodule from the namespace.

(apologies for the jargon :( )
