### ISSUE TITLE
Reducing template device memory footprint with multiple GPUs

### ISSUE THREAD

**Issue by beridel** [beridel/fast_matched_filter#24]
I've been playing with lots of templates recently, and even with beefy Tesla V100's, I've started to run into situations where there is not enough memory to store the CC sum outputs.

I need to spend some time thinking about it and staring at the code, but shouldn't it be possible to reduce the amount of memory needed on each GPU if there are multiple GPUs? i.e. if there are 4 GPUs, then the amount of memory needed on each should just be a 1/4 of the total?

This could also be useful for those using the non-Tesla GPUs that have much less memory.

**Comment by ebeauce** [comment]
Just a comment:
For now, the GPUs are "racing" against each other and each of them process the next template in queue. The final list of templates processed by each GPU depends on how fast they were. This has the advantage of being quick and easy to implement (and requires that all GPUs have all templates in memory).

**Comment by ebeauce** [comment]
3 years later, I have come to realize that the issue was not at all the algorithm itself but just the integer data type used to represent the array sizes...
