### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by beridel** [beridel/fast_matched_filter#3]
The easiest way to make this program useful for both python and matlab users is to build everything via the Makefile (and not via distutils in setup.py).  That way matlab users don't have to know how to make setup.py work.

So it is possible to call the Makefile from setup.py for python users?

**Comment by calum-chamberlain** [comment]
Agreed, and yes it is - it would still use either distils or setup tools, but we can overload their build and install commands so that they call the Makefile.

**Comment by calum-chamberlain** [comment]
See PR #4

**Comment by beridel** [comment]
Yes, I will take a look at it, don't worry!  We're going to France for three weeks at the end of the week, and I'm trying to finish up a revision before that.  Hopefully tomorrow.
