### ISSUE TITLE
GPU compilation error

### ISSUE THREAD

**Issue by calum-chamberlain** [beridel/fast_matched_filter#5]
Compiling with the Makefile (`make python_gpu`) results in:
```bash
nvcc -O3 -Xcompiler "-fopenmp -fPIC -march=native -ftree-vectorize" -Xlinker -lgomp -arch=sm_35 --shared fast_matched_filter/src/matched_filter.cu -o fast_matched_filter/lib/matched_filter_GPU.so
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
Makefile:43: recipe for target 'fast_matched_filter/lib/matched_filter_GPU.so' failed
make: *** [fast_matched_filter/lib/matched_filter_GPU.so] Error 1
```

I made this error disappear by changing the CFLAGS_GPU line in the Makefile to:
```
CFLAGS_GPU=-D_FORCE_INLINES -Xcompiler "-fopenmp -fPIC -march=native -ftree-vectorize" -Xlinker -lgomp
```
This includes the `-D_FORCE_INLINES` argument.  I don't know if this is the thing to do in general?

I'm running the following version of nvcc (which may be out of date!):
```
>> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

**Comment by beridel** [comment]
Super weird... I'll look into it a bit more and more importantly see if it changes anything when I actually run it.  I'll do that tomorrow.

**Comment by beridel** [comment]
Real quick: what's your version of gcc?

**Comment by calum-chamberlain** [comment]
```bash
>> gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```
**20160609** ?

**Comment by beridel** [comment]
Ya, that's the problem.  I now remember that CUDA 7.5 is not happy with any gcc whose version >=4.9.  After a super quick google search (the same I assume you did...), it seems that adding that option makes it compile with later versions of gcc.  But compiling and running are different animals, so I will see tomorrow if it not just compiles but also runs well with gcc >=4.9.

**Comment by calum-chamberlain** [comment]
Sweet thanks!

I'm currently running into an error (having compiled using that extra flag) of:
```bash
libgomp: Thread creation failed: Resource temporarily unavailable
```
But I have a feeling it is an issue on my end with how I have the GPU set-up.  If you get the same error tomorrow let me know.
It looks like it is trying to allocate more resources than it thinks it has. Will play for half an hour and see while I procrastinate from writing lectures.

**Comment by beridel** [comment]
Yes, that does look like what is happening.  What sort of graphics card do you have?

**Comment by calum-chamberlain** [comment]
I'm trying things out on our cluster - I may be the first to try and use the GPU cards.  From `lspci` we have:
```bash
3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
```

**Comment by beridel** [comment]
If I remember from when Laura was at MIT, the cluster uses slurm right?

If so, you have to specifically ask for access to GPUs with --gres=gpu:1 for one GPU or --gres=gpu:2 for 2 GPUs.  Each K80 has two GPUs, so you can ask for up to 4 on that machine.

Let's first make sure you're doing that.

**Comment by calum-chamberlain** [comment]
Ah no, different cluster, but well remembered, this is our local cluster that has no job management and everything available.  The code sees the GPUs (I added a print line in the match_filter.cu: `printf("Will work using %i GPU threads\n", nGPUs);` - which outputs: `Will work using 32766 GPU threads`).  If I limit nGPUs to say 1000 then I get different errors about memory not being available.

I think I'm going to talk to our cluster manager here about it and see whether it is a set-up issue first.

**Comment by beridel** [comment]
There is something already wrong if nGPUs = 37266.  It should be equal to the number of GPUS, i.e. 1 or 4, etc.

**Comment by calum-chamberlain** [comment]
Good to know! I had assumed it was the number of threads!

**Comment by beridel** [comment]
Nope, the OpenMP loop is there to distribute templates to different GPU, where each thread handles one GPU.

**Comment by calum-chamberlain** [comment]
Yup, I'm fairly sure it is an issue with our libraries, will let you know what we find out.

**Comment by ebeauce** [comment]
Hello,

Thank you Calum for joining us in this project ! By the way, I am Eric Beaucé, a PhD student at MIT and I have been working on this kind of codes for 1 year and a half.

The addition of -D_FORCE_INLINE didn't solve the compilation problem for me. But initially, I don't have the same error:

`In file included from /cm/shared/apps/cuda75/sdk/7.5.18/bin/..//include/cuda_runtime.h:76:0,
                 from <command-line>:0:
/cm/shared/apps/cuda75/sdk/7.5.18/bin/..//include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^~~~~
make: *** [fast_matched_filter/lib/matched_filter_GPU.so] Error 1
`

This error doesn't mention any problem about function declarations but is really about the gcc's version.

**Comment by beridel** [comment]
It's strange that your older version of the cuda toolkit (7.5.17) doesn't say that your gcc version isn't supported...

In any case, I'm thinking we should just accept cuda is a pain, and tell users that they need to have a supported version of gcc (cf. the doc for CUDA toolkit 8: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz3x7mwvZrG).

**Comment by calum-chamberlain** [comment]
Hi @ebeauce, good to hear from you! Thanks for letting me play with this - looks like you guys have done some really good work! And thanks for sharing it with the world!

I'm fairly sure this issue can be closed and I should just apologies for bothering you both with this - after further googling I am also surprised that nvcc didn't complain about gcc.  I'm fairly sure all this can be sorted by setting up our compilers properly.

Apologies again, and thanks for your advice!
